### ISSUE TITLE
kubernetes + rtpproxy

### ISSUE THREAD

**Issue by sergey-safarov** [2600hz/kazoo-configs-kamailio#110]
I stuck with RTP issues when kazoo deplayed in kubernetes environment and present devices connected via VPN.

I not able properly handle this issues on FreeSwitch side. more details at [FS-10990](https://freeswitch.org/jira/browse/FS-10990)
I thinking about addition of rtpproxy support in kamailio config.

Is exist any suggestion how to implement this feature addition?

**Comment by lazedo** [comment]
Hi @sergey-safarov ,
`rtpproxy` is something we don't want to add for now. the reason you're invoking seems related to a `dns` issue that is exposed in freeswitch but may be exposed in other servers too. i think you should try to resolve this on `kubernetes` and/or `freeswitch`
